# Generated by Django 3.2.10 on 2022-01-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users_avatars'),
        ),
        migrations.AddField(
            model_name='user',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='background_images'),
        ),
    ]
