# Generated by Django 3.2.10 on 2022-01-13 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('slug', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('visibility', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=7)),
                ('audio', models.FileField(upload_to='audios')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='main.genre')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
