# Generated by Django 3.2.10 on 2022-01-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default='default_genre', max_length=100),
            preserve_default=False,
        ),
    ]
