# Generated by Django 3.2.10 on 2022-01-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='audio',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
